use crate::classify;
use crate::model::PatentRecord;
use crate::taxonomy::Taxonomy;
use anyhow::{Context, Result};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::fs::File;
use std::io::{BufRead, BufReader, BufWriter, Write};
use std::path::Path;

pub fn read_json_lines(path: &Path) -> Result<Vec<Value>> {
    let file = File::open(path).with_context(|| format!("cannot open {}", path.display()))?;
    let mut values = Vec::new();
    for (idx, line) in BufReader::new(file).lines().enumerate() {
        let line = line.with_context(|| format!("cannot read {} line {}", path.display(), idx + 1))?;
        if line.trim().is_empty() {
            continue;
        }
        let value = serde_json::from_str(&line)
            .with_context(|| format!("invalid JSON at {}:{}", path.display(), idx + 1))?;
        values.push(value);
    }
    Ok(values)
}

pub fn read_records(path: &Path) -> Result<Vec<PatentRecord>> {
    read_json_lines(path)?
        .into_iter()
        .enumerate()
        .map(|(idx, value)| {
            serde_json::from_value(value)
                .with_context(|| format!("invalid patent record at {}:{}", path.display(), idx + 1))
        })
        .collect()
}

pub fn unwrap_google(value: Value) -> Result<Value> {
    match value.get("raw_record") {
        Some(Value::String(raw)) => serde_json::from_str(raw).context("raw_record is not JSON"),
        Some(other) => Ok(other.clone()),
        None => Ok(value),
    }
}

pub fn write_records(path: &Path, records: &[PatentRecord]) -> Result<()> {
    let file = File::create(path).with_context(|| format!("cannot create {}", path.display()))?;
    let mut writer = BufWriter::new(file);
    for record in records {
        serde_json::to_writer(&mut writer, record)?;
        writer.write_all(b"\n")?;
    }
    writer.flush()?;
    Ok(())
}

pub fn write_values(path: &Path, values: &[Value]) -> Result<()> {
    let file = File::create(path).with_context(|| format!("cannot create {}", path.display()))?;
    let mut writer = BufWriter::new(file);
    for value in values {
        serde_json::to_writer(&mut writer, value)?;
        writer.write_all(b"\n")?;
    }
    writer.flush()?;
    Ok(())
}

pub fn record_hash(record: &PatentRecord) -> Result<String> {
    Ok(hex::encode(Sha256::digest(serde_json::to_vec(record)?)))
}

pub fn write_stage_sql(path: &Path, records: &[PatentRecord], taxonomy: &Taxonomy) -> Result<()> {
    let file = File::create(path).with_context(|| format!("cannot create {}", path.display()))?;
    let mut writer = BufWriter::new(file);
    writeln!(writer, "-- Generated by battery-patent-miner. Staging only: no bd.* writes.")?;
    writeln!(writer, "BEGIN;")?;
    for record in records {
        let validation = classify::validate(record, taxonomy);
        let state = if validation.valid() { "valid" } else { "invalid" };
        let hash = record_hash(record)?;
        let candidate_uid = format!("patent-candidate/{hash}");
        let family_key = record
            .family_keys
            .first()
            .map(|f| format!("{}:{}:{}", f.provider, f.kind, f.id))
            .unwrap_or_else(|| "missing".to_string());
        let payload = serde_json::to_string(record)?;
        let relevance = serde_json::to_string(&record.annotations)?;
        let validation_json = serde_json::to_string(&json!({
            "errors": validation.errors,
            "warnings": validation.warnings
        }))?;
        writeln!(
            writer,
            "INSERT INTO bd_stage.patent_candidate (candidate_uid, publication_number, family_key, source_provider, source_record_id, source_record_url, taxonomy_version, record_sha256, payload, relevance_reasons, validation, state) VALUES ({}, {}, {}, {}, {}, {}, {}, {}, {}::jsonb, {}::jsonb, {}::jsonb, '{}'::bd.patent_candidate_state) ON CONFLICT (source_provider, source_record_id) DO NOTHING;",
            sql_string(&candidate_uid),
            sql_string(&record.publication_number),
            sql_string(&family_key),
            sql_string(&record.source.provider),
            sql_string(&record.source.record_id),
            sql_optional(record.source.record_url.as_deref()),
            sql_string(&record.taxonomy_version),
            sql_string(&hash),
            sql_string(&payload),
            sql_string(&relevance),
            sql_string(&validation_json),
            state
        )?;
    }
    writeln!(writer, "COMMIT;")?;
    writer.flush()?;
    Ok(())
}

fn sql_string(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn sql_optional(value: Option<&str>) -> String {
    value.map(sql_string).unwrap_or_else(|| "NULL".to_string())
}
