use crate::taxonomy::Taxonomy;
use anyhow::{bail, Result};
use chrono::NaiveDate;

pub fn google_bigquery(taxonomy: &Taxonomy, from: &str, to: &str) -> Result<String> {
    let from_date = NaiveDate::parse_from_str(from, "%Y-%m-%d")?;
    let to_date = NaiveDate::parse_from_str(to, "%Y-%m-%d")?;
    if to_date < from_date {
        bail!("--to precedes --from");
    }
    let from_int = from_date.format("%Y%m%d");
    let to_int = to_date.format("%Y%m%d");
    let primary = regex_prefixes(
        taxonomy
            .coverage_contract
            .primary_prefixes
            .iter()
            .chain(taxonomy.coverage_contract.historical_prefixes.iter()),
    );
    let text_expr = "LOWER(CONCAT(ARRAY_TO_STRING(ARRAY(SELECT x.text FROM UNNEST(p.title) x), ' '), ' ', ARRAY_TO_STRING(ARRAY(SELECT x.text FROM UNNEST(p.abstract) x), ' ')))";

    let mut clauses = vec![format!(
        "EXISTS (SELECT 1 FROM UNNEST(p.cpc) c WHERE REGEXP_CONTAINS(REPLACE(UPPER(c.code), ' ', ''), r'^({primary})'))"
    ), format!(
        "EXISTS (SELECT 1 FROM UNNEST(p.ipc) c WHERE REGEXP_CONTAINS(REPLACE(UPPER(c.code), ' ', ''), r'^({primary})'))"
    )];
    for profile in &taxonomy.coverage_contract.cross_domain_profiles {
        let prefixes = regex_prefixes(profile.classification_prefixes.iter());
        let terms = profile
            .required_terms
            .iter()
            .map(|term| regex_escape(term))
            .collect::<Vec<_>>()
            .join("|");
        clauses.push(format!(
            "((EXISTS (SELECT 1 FROM UNNEST(p.cpc) c WHERE REGEXP_CONTAINS(REPLACE(UPPER(c.code), ' ', ''), r'^({prefixes})'))\n      OR EXISTS (SELECT 1 FROM UNNEST(p.ipc) c WHERE REGEXP_CONTAINS(REPLACE(UPPER(c.code), ' ', ''), r'^({prefixes})')))\n     AND REGEXP_CONTAINS({text_expr}, r'(?i)({terms})'))"
        ));
    }

    Ok(format!(
        "-- Generated by battery-patent-miner. This is a discovery query, not a\n\
         -- legal/FTO search. Query cost and credentials require explicit user approval.\n\
         -- Run with BigQuery in the US multi-region and stream the raw_record\n\
         -- column as NDJSON into: patent-miner ingest-google.\n\
         SELECT TO_JSON_STRING(p) AS raw_record\n\
           FROM `patents-public-data.patents.publications` p\n\
          WHERE p.publication_date BETWEEN {from_int} AND {to_int}\n\
            AND (\n              {}\n            )\n\
          ORDER BY p.publication_number;\n",
        clauses.join("\n              OR ")
    ))
}

fn regex_prefixes<'a>(values: impl Iterator<Item = &'a String>) -> String {
    values
        .map(|value| {
            let normalized: String = value
                .chars()
                .filter(|c| !c.is_whitespace() && *c != '-' && *c != '.')
                .collect();
            regex_escape(&normalized)
        })
        .collect::<Vec<_>>()
        .join("|")
}

fn regex_escape(value: &str) -> String {
    let mut out = String::new();
    for c in value.chars() {
        if "\\.^$|?*+()[]{}".contains(c) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::taxonomy::*;

    #[test]
    fn plan_is_date_bounded_and_classification_first() {
        let taxonomy = Taxonomy {
            taxonomy_version: "1.0.0".into(),
            coverage_contract: CoverageContract {
                primary_prefixes: vec!["H01M10".into()],
                historical_prefixes: vec!["H01M2".into()],
                cross_domain_profiles: vec![],
                exclusion_profiles: vec![],
            },
            taxa: vec![],
        };
        let sql = google_bigquery(&taxonomy, "2026-08-01", "2026-08-24").unwrap();
        assert!(sql.contains("BETWEEN 20260801 AND 20260824"));
        assert!(sql.contains("H01M10|H01M2"));
        assert!(sql.contains("TO_JSON_STRING(p)"));
    }
}
