#!/usr/bin/env bash
# Build the discharge model and inline it into the site.
#
# WHY IT IS INLINED
# -----------------
# web/sim.js carries the module as base64 inside a <script> tag rather than as
# a .wasm file the page fetches. A fetch of a file:// URL is blocked by every
# browser, so a fetched module would make the site work on a server and fail
# from a folder. The whole module is under two kilobytes; inlining it costs
# nothing and the page keeps working wherever it is opened.
#
#     tools/build_wasm.sh            # rebuild web/sim.js
#     tools/build_wasm.sh --check    # fail if web/sim.js is stale (needs Rust)
#
# Rust is not required to work on the site: web/sim.js is committed. It is
# required to change the model in wasm/battery-sim/src/lib.rs.
set -euo pipefail
cd "$(dirname "$0")/.."

command -v cargo >/dev/null || { echo "cargo not found: install Rust from https://rustup.rs"; exit 1; }
rustup target list --installed 2>/dev/null | grep -q wasm32-unknown-unknown \
  || rustup target add wasm32-unknown-unknown

cargo build --manifest-path wasm/battery-sim/Cargo.toml \
            --release --target wasm32-unknown-unknown
WASM=wasm/battery-sim/target/wasm32-unknown-unknown/release/battery_sim.wasm

OUT=$(mktemp)
{
  echo "/* GENERATED by tools/build_wasm.sh -- do not edit."
  echo "   The cell discharge model from wasm/battery-sim, compiled to"
  echo "   WebAssembly and inlined so the page runs from a file:// path too."
  echo "   $(wc -c < "$WASM") bytes of WebAssembly. */"
  printf 'window.BD_SIM_WASM = "%s";\n' "$(base64 -w0 < "$WASM")"
} > "$OUT"

if [ "${1:-}" = "--check" ]; then
  if cmp -s "$OUT" web/sim.js; then
    echo "web/sim.js is up to date ($(wc -c < "$WASM") bytes of wasm)"
    rm -f "$OUT"; exit 0
  fi
  echo "web/sim.js is stale. Run: tools/build_wasm.sh" >&2
  rm -f "$OUT"; exit 1
fi

mv "$OUT" web/sim.js
chmod 644 web/sim.js
echo "wrote web/sim.js: $(wc -c < "$WASM") bytes of wasm, $(wc -c < web/sim.js) bytes on the page"
