#!/usr/bin/env python3
"""Export the graph projection for Neo4j (or any property-graph import).

bd_graph.node and bd_graph.edge are the projection; this writes them as two
CSV files plus a Cypher script that loads them with LOAD CSV, and refreshes
the projection first so the export is never behind the tables.

    python tools/export_graph.py [dbname] [outdir]        # default graph/

Files:
    nodes.csv     key,label,uid,title,props      (props is a JSON string)
    edges.csv     src,dst,rel,props
    load.cypher   LOAD CSV statements; run with cypher-shell after copying the
                  CSVs into Neo4j's import directory
"""
import csv
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = sys.argv[1] if len(sys.argv) > 1 else "batterydb"
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, "graph")
os.makedirs(OUT, exist_ok=True)


def rows(sql):
    r = subprocess.run(["psql", "-tAq", "-d", DB, "-c", sql], capture_output=True, text=True, check=True)
    return json.loads(r.stdout.strip() or "[]")


subprocess.run(["psql", "-q", "-d", DB, "-c", "SELECT bd_graph.refresh();"], check=True,
               capture_output=True)
nodes = rows("SELECT coalesce(json_agg(row_to_json(n) ORDER BY n.node_key),'[]') FROM bd_graph.node n;")
edges = rows("SELECT coalesce(json_agg(row_to_json(e) ORDER BY e.src_key, e.rel, e.dst_key),'[]') "
             "FROM bd_graph.edge e;")

with open(os.path.join(OUT, "nodes.csv"), "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["key", "label", "uid", "title", "props"])
    for n in nodes:
        w.writerow([n["node_key"], n["label"], n["uid"], n["title"], json.dumps(n["props"], sort_keys=True)])
with open(os.path.join(OUT, "edges.csv"), "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["src", "dst", "rel", "props"])
    for e in edges:
        w.writerow([e["src_key"], e["dst_key"], e["rel"], json.dumps(e["props"], sort_keys=True)])

labels = sorted({n["label"] for n in nodes})
rels = sorted({e["rel"] for e in edges})
cypher = ["// battery-data graph projection. GENERATED by tools/export_graph.py.",
          "// Copy nodes.csv and edges.csv into Neo4j's import directory, then:",
          "//   cypher-shell -f load.cypher",
          "CREATE CONSTRAINT bd_key IF NOT EXISTS FOR (n:Node) REQUIRE n.key IS UNIQUE;",
          "LOAD CSV WITH HEADERS FROM 'file:///nodes.csv' AS row",
          "CALL { WITH row",
          "  MERGE (n:Node {key: row.key})",
          "  SET n.uid = row.uid, n.title = row.title, n.props = row.props",
          "} IN TRANSACTIONS OF 2000 ROWS;"]
for label in labels:
    cypher.append(f"MATCH (n:Node) WHERE n.key STARTS WITH '{ {n['node_key'].split(':')[0] for n in nodes if n['label']==label}.pop() }:' SET n:{label};")
cypher += ["LOAD CSV WITH HEADERS FROM 'file:///edges.csv' AS row",
           "CALL { WITH row",
           "  MATCH (a:Node {key: row.src}), (b:Node {key: row.dst})",
           "  CALL apoc.create.relationship(a, row.rel, {props: row.props}, b) YIELD rel",
           "  RETURN count(rel) AS c",
           "} IN TRANSACTIONS OF 2000 ROWS;",
           "// Without APOC, load one relationship type at a time:",
           *[f"// MATCH (a:Node {{key: row.src}}), (b:Node {{key: row.dst}}) WHERE row.rel = '{r}' CREATE (a)-[:{r}]->(b);" for r in rels]]
with open(os.path.join(OUT, "load.cypher"), "w", encoding="utf-8") as f:
    f.write("\n".join(cypher) + "\n")
print(f"wrote {OUT}/nodes.csv ({len(nodes)} nodes), edges.csv ({len(edges)} edges), load.cypher "
      f"({len(labels)} labels, {len(rels)} relationship types)")
