/* ============================================================
   battery-data — the shared runtime
   ------------------------------------------------------------
   Every page loads this once and the browser caches it. It
   holds the drawing, the number formatting and the two
   interactive parts; the pages themselves are static HTML
   generated by tools/build_site.py, so nothing here has to
   render a page before a reader can read it.

   The one rule that shapes this file: a page only ever carries
   the data it shows. The library's 600 values live on the 64
   product pages, one page each, not in a blob every visitor
   downloads to look at the home page.
   ============================================================ */
"use strict";

/* ---- numbers ----------------------------------------------------------- */
function num(v) {
  if (v == null || v === "") return "";
  const n = Number(v);
  if (!isFinite(n)) return String(v);
  const abs = Math.abs(n);
  const dp = abs >= 1000 ? 0 : abs >= 100 ? 1 : abs >= 1 ? 2 : 4;
  return n.toLocaleString("en-US", {maximumFractionDigits: dp});
}
const esc = s => String(s == null ? "" : s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const plural = (n, one, many) => n + " " + (n === 1 ? one : (many || one + "s"));

/* ============================================================
   The drawing
   ------------------------------------------------------------
   Two projections of the same solids: a three-quarter view for
   a single product, and a true isometric for the landscape and
   the product glyphs.

   Dimensions arrive already resolved, in millimetres, on the
   record's `d`. Which of a document's three published numbers
   is the height is decided once, in Python, where the rule can
   be written down next to the data it applies to.

   Every gradient in the file is defined ONCE, in a sprite the
   page carries at the top of the body, and referenced by id.
   Sixty-four tiles used to mean 320 gradient definitions; they
   now mean none.
   ============================================================ */
const SPRITE = `<svg width="0" height="0" style="position:absolute" aria-hidden="true" focusable="false"><defs>
  <linearGradient id="mF" x1="0" y1="0" x2="1" y2="0">
    <stop offset="0" stop-color="var(--metal-2)"/><stop offset=".09" stop-color="var(--metal-hi)"/>
    <stop offset=".46" stop-color="var(--metal-1)"/><stop offset=".84" stop-color="var(--metal-2)"/>
    <stop offset="1" stop-color="var(--metal-3)"/></linearGradient>
  <linearGradient id="mT" x1="0" y1="1" x2="0" y2="0">
    <stop offset="0" stop-color="var(--metal-1)"/><stop offset="1" stop-color="var(--metal-hi)"/></linearGradient>
  <linearGradient id="mS" x1="0" y1="0" x2="1" y2="0">
    <stop offset="0" stop-color="var(--metal-3)"/><stop offset="1" stop-color="var(--metal-2)"/></linearGradient>
  <radialGradient id="mSh" cx=".5" cy=".5" r=".5">
    <stop offset="0" stop-color="rgba(0,0,0,.30)"/><stop offset="1" stop-color="rgba(0,0,0,0)"/></radialGradient>
  <linearGradient id="iT" x1="0" y1="0" x2=".7" y2="1">
    <stop offset="0" stop-color="var(--iso-1)"/><stop offset="1" stop-color="var(--iso-2)"/></linearGradient>
  <linearGradient id="iL" x1="0" y1="0" x2="0" y2="1">
    <stop offset="0" stop-color="var(--iso-3)"/><stop offset="1" stop-color="var(--iso-4)"/></linearGradient>
  <linearGradient id="iR" x1="0" y1="0" x2="0" y2="1">
    <stop offset="0" stop-color="var(--iso-2)"/><stop offset="1" stop-color="var(--iso-3)"/></linearGradient>
  <linearGradient id="bT" x1="0" y1="0" x2=".7" y2="1">
    <stop offset="0" stop-color="var(--iso-b1)"/><stop offset="1" stop-color="var(--iso-b2)"/></linearGradient>
  <linearGradient id="bL" x1="0" y1="0" x2="0" y2="1">
    <stop offset="0" stop-color="var(--iso-b3)"/><stop offset="1" stop-color="var(--iso-b4)"/></linearGradient>
  <linearGradient id="bR" x1="0" y1="0" x2="0" y2="1">
    <stop offset="0" stop-color="var(--iso-b2)"/><stop offset="1" stop-color="var(--iso-b3)"/></linearGradient>
  <radialGradient id="iSh" cx=".5" cy=".5" r=".5">
    <stop offset="0" stop-color="var(--iso-shadow)"/><stop offset="1" stop-color="transparent"/></radialGradient>
  <linearGradient id="labFill" x1="0" y1="0" x2="0" y2="1">
    <stop offset="0" stop-color="var(--acc-2)" stop-opacity=".22"/>
    <stop offset="1" stop-color="var(--acc-2)" stop-opacity="0"/></linearGradient>
</defs></svg>`;

/* ---- one product, three-quarter view ----------------------------------- */
const ART_CACHE = new Map();
function art(r, opt) {
  opt = opt || {};
  const key = r.uid + "|" + (opt.max || 0) + "|" + (opt.scale || 0) + "|" + (opt.reflect ? 1 : 0);
  const hit = ART_CACHE.get(key);
  if (hit) return hit;

  const box = opt.max || 150, ghost = !r.d;
  const d = r.d || (r.shape === "cyl" ? {shape: "cyl", d: 21, h: 70}
                    : {shape: "box", w: 148, h: 200, t: 52});
  const assembled = r.kind === "module" || r.kind === "pack" || r.kind === "system";
  const dep = d.shape === "box" ? d.t * 0.3 : 0;          /* cabinet projection */
  const wmm = (d.shape === "cyl" ? d.d : d.w) + dep, hmm = d.h + dep;
  const scale = opt.scale || Math.min(box / wmm, box / hmm);
  const W = wmm * scale, H = hmm * scale, pad = 7, floor = 9;
  const refl = opt.reflect ? H * .42 : 0;
  const s = [];

  const EDGE = 'stroke="var(--metal-edge)" stroke-width=".8" stroke-linejoin="round"';
  const OUT = 'fill="none" stroke="var(--metal-edge)" stroke-width="1.2" stroke-dasharray="5 4" stroke-linejoin="round" opacity=".85"';
  const face = ghost ? OUT : `fill="url(#mF)" ${EDGE}`;

  if (!ghost) s.push(`<ellipse cx="${pad + W / 2}" cy="${pad + H + floor - 3}" rx="${W * .44}" ry="4.5" fill="url(#mSh)"/>`);

  if (d.shape === "cyl") {
    const w = d.d * scale, h = d.h * scale, x = pad + (W - w) / 2, y = pad;
    const ry = Math.min(w * .16, h * .34), nub = Math.max(w * .34, 3.5);
    s.push(`<path d="M${x} ${y + ry} v${h - ry * 2} a${w / 2} ${ry} 0 0 0 ${w} 0 v${-(h - ry * 2)}" ${face}/>`);
    s.push(`<ellipse cx="${x + w / 2}" cy="${y + ry}" rx="${w / 2}" ry="${ry}" ${ghost ? OUT : `fill="url(#mT)" ${EDGE}`}/>`);
    if (!ghost) {
      s.push(`<ellipse cx="${x + w / 2}" cy="${y + ry}" rx="${w * .35}" ry="${ry * .6}" fill="var(--metal-2)" stroke="var(--metal-edge)" stroke-width=".5" opacity=".9"/>`);
      s.push(`<ellipse cx="${x + w / 2}" cy="${y + ry * .55}" rx="${nub / 2}" ry="${ry * .28}" fill="var(--metal-hi)" stroke="var(--metal-edge)" stroke-width=".5"/>`);
      s.push(`<rect x="${x + w / 2 - nub / 2}" y="${y + ry * .55}" width="${nub}" height="${ry * .45}" fill="var(--metal-1)"/>`);
      s.push(`<line x1="${x + w * .87}" y1="${y + ry * 1.5}" x2="${x + w * .87}" y2="${y + h - ry * .7}" stroke="var(--metal-edge)" stroke-width=".5" opacity=".3"/>`);
      s.push(`<path d="M${x} ${y + ry * 2.1} a${w / 2} ${ry} 0 0 0 ${w} 0" fill="none" stroke="var(--metal-edge)" stroke-width=".5" opacity=".35"/>`);
    }
  } else {
    const w = d.w * scale, h = d.h * scale, dz = dep * scale;
    const x = pad, y = pad + dz, rr = Math.min(w, h) * .035;
    s.push(`<path d="M${x} ${y} l${dz} ${-dz} h${w} l${-dz} ${dz} z" ${ghost ? OUT : `fill="url(#mT)" ${EDGE}`}/>`);
    s.push(`<path d="M${x + w} ${y} l${dz} ${-dz} v${h} l${-dz} ${dz} z" ${ghost ? OUT : `fill="url(#mS)" ${EDGE}`}/>`);
    s.push(`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rr}" ${face}/>`);
    if (!ghost) {
      s.push(`<rect x="${x + w * .035}" y="${y + h * .022}" width="${w * .93}" height="${h * .956}" rx="${rr}" fill="none" stroke="var(--metal-edge)" stroke-width=".5" opacity=".28"/>`);
      const tw = Math.max(w * .13, 3.2), rise = Math.max(h * .012, 1.6);
      [x + w * .2 - tw / 2, x + w * .8 - tw / 2].forEach(tx => {
        s.push(`<rect x="${tx}" y="${y - rise}" width="${tw}" height="${rise + 1}" fill="var(--metal-2)" stroke="var(--metal-edge)" stroke-width=".5"/>`);
        s.push(`<path d="M${tx} ${y - rise} l${dz * .55} ${-dz * .55} h${tw} l${-dz * .55} ${dz * .55} z" fill="var(--metal-hi)" stroke="var(--metal-edge)" stroke-width=".5"/>`);
      });
      if (assembled)
        for (let i = 1; i < 4; i++)
          s.push(`<line x1="${x + w * i / 4}" y1="${y + h * .1}" x2="${x + w * i / 4}" y2="${y + h * .9}" stroke="var(--metal-edge)" stroke-width=".5" opacity=".45"/>`);
    }
  }

  const gid = "b" + ART_CACHE.size;
  const body = `<g id="${gid}">${s.join("")}</g>`;
  const mask = refl && !ghost
    ? `<mask id="${gid}m"><rect x="0" y="${pad + H}" width="${W + pad * 2}" height="${refl}" fill="url(#reflFade)"/></mask>`
    : "";
  const mirror = refl && !ghost
    ? `<defs>${mask}<linearGradient id="reflFade" x1="0" y1="0" x2="0" y2="1">
         <stop offset="0" stop-color="#fff" stop-opacity=".42"/><stop offset="1" stop-color="#fff" stop-opacity="0"/>
       </linearGradient></defs>
       <use href="#${gid}" transform="translate(0 ${2 * (pad + H)}) scale(1 -1)" mask="url(#${gid}m)" opacity=".5"/>`
    : "";
  const h = H + pad * 2 + floor + refl;
  const label = ghost ? "no published dimensions" : d.label;
  const out = {svg: `<svg viewBox="0 0 ${W + pad * 2} ${h}" width="${Math.round(W + pad * 2)}" height="${Math.round(h)}" role="img" aria-label="${esc(r.name)}, ${esc(label)}">${body}${mirror}</svg>`,
               label: label, ghost: ghost};
  ART_CACHE.set(key, out);
  return out;
}

/* ============================================================
   The isometric landscape
   ------------------------------------------------------------
   Camera over the +x +y corner:
       sx = (x - y)·cos30        sy = (x + y)·sin30 - z
   ============================================================ */
const C30 = Math.cos(Math.PI / 6), S30 = 0.5;
const px = (x, y, z, s) => [(x - y) * C30 * s, ((x + y) * S30 - z) * s];

function isoBox(x, y, z, w, dp, h, s, f) {
  const p = (X, Y, Z) => px(X, Y, Z, s).join(" ");
  const poly = (pts, fill) => `<polygon points="${pts}" fill="${fill}" stroke="${f.edge}" stroke-width=".7" stroke-linejoin="round"/>`;
  return poly([p(x, y, z + h), p(x + w, y, z + h), p(x + w, y + dp, z + h), p(x, y + dp, z + h)].join(" "), f.top)
       + poly([p(x, y + dp, z), p(x + w, y + dp, z), p(x + w, y + dp, z + h), p(x, y + dp, z + h)].join(" "), f.left)
       + poly([p(x + w, y, z), p(x + w, y + dp, z), p(x + w, y + dp, z + h), p(x + w, y, z + h)].join(" "), f.right);
}

function isoCyl(x, y, z, r, h, s, f) {
  const rx = r * C30 * Math.SQRT2 * s, ry = r * S30 * Math.SQRT2 * s;
  const top = px(x, y, z + h, s), bot = px(x, y, z, s);
  return `<path d="M${top[0] - rx} ${top[1]} v${bot[1] - top[1]} a${rx} ${ry} 0 0 0 ${rx * 2} 0 v${top[1] - bot[1]} z"
            fill="${f.left}" stroke="${f.edge}" stroke-width=".7"/>
          <ellipse cx="${top[0]}" cy="${top[1]}" rx="${rx}" ry="${ry}" fill="${f.top}" stroke="${f.edge}" stroke-width=".7"/>
          <ellipse cx="${top[0]}" cy="${top[1]}" rx="${rx * .52}" ry="${ry * .52}" fill="${f.right}" stroke="${f.edge}" stroke-width=".5" opacity=".8"/>`;
}

const ISO_W = {top: "url(#iT)", left: "url(#iL)", right: "url(#iR)", edge: "var(--iso-edge)"};
const ISO_B = {top: "url(#bT)", left: "url(#bL)", right: "url(#bR)", edge: "var(--iso-blue-edge)"};

/* One product standing at (x, y) on the plane. */
function isoProduct(r, x, y, s) {
  const d = r.d;
  if (!d) return null;
  const assembled = r.kind === "module" || r.kind === "pack" || r.kind === "system";
  const F = assembled ? ISO_B : ISO_W;
  let body, w, dp, h;

  if (d.shape === "cyl") {
    w = dp = d.d; h = d.h;
    body = isoCyl(x + d.d / 2, y + d.d / 2, 0, d.d / 2, d.h, s, F);
  } else {
    w = d.w; dp = d.t; h = d.h;
    body = isoBox(x, y, 0, w, dp, h, s, F);
    const tw = w * .13, td = dp * .34, th = Math.max(h * .014, 2 / s);
    [w * .2, w * .8 - tw].forEach(o => {
      body += isoBox(x + o, y + dp * .33, h, tw, td, th, s,
                     {top: F.top, left: F.right, right: F.right, edge: F.edge});
    });
    if (assembled)
      for (let i = 1; i < 4; i++) {
        const a = px(x + w * i / 4, y + dp, 0, s), b = px(x + w * i / 4, y + dp, h, s);
        body += `<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="var(--iso-edge)" stroke-width=".6" opacity=".5"/>`;
      }
  }
  const c = px(x + w / 2, y + dp / 2, 0, s);
  const shadow = `<ellipse cx="${c[0]}" cy="${c[1]}" rx="${(w + dp) * .42 * C30 * s}" ry="${(w + dp) * .40 * S30 * s}" fill="url(#iSh)"/>`;
  return {svg: shadow + body, pin: px(x + w / 2, y + dp / 2, h, s), depth: x + y, h: h,
          foot: px(x + w / 2, y + dp / 2, 0, s)};
}

/* The whole plane: a grid, the current running between the objects, and the
   objects themselves, each with a marker that opens its page. */
function landscape(list, opt) {
  opt = opt || {};
  const foot = r => r.d.shape === "cyl" ? r.d.d : Math.max(r.d.w, r.d.t);
  const cells = list.filter(r => r.d).slice(0, 7).sort((a, b) => b.d.h - a.d.h);
  if (!cells.length) return "";
  const pitch = Math.max(...cells.map(foot)) * 1.15;
  const GRID = [[0, 0], [1, 0], [0, 1], [2, 0], [1, 1], [0, 2], [2, 1], [1, 2], [2, 2]];

  const s = 1;
  /* one pass: position, draw and remember, rather than drawing twice */
  const drawn = cells.map((r, i) => {
    const g = GRID[i], d = r.d;
    const w = d.shape === "cyl" ? d.d : d.w, dp = d.shape === "cyl" ? d.d : d.t;
    const at = [g[0] * pitch + (pitch - w) / 2, g[1] * pitch + (pitch - dp) / 2];
    return {r: r, at: at, w: w, dp: dp, out: isoProduct(r, at[0], at[1], s)};
  });

  const m = pitch * .3;
  const O = {x: Math.min(...drawn.map(o => o.at[0])) - m, y: Math.min(...drawn.map(o => o.at[1])) - m};
  const PLOT = {w: Math.max(...drawn.map(o => o.at[0] + o.w)) + m - O.x,
                d: Math.max(...drawn.map(o => o.at[1] + o.dp)) + m - O.y};

  const pts = [];
  [[0, 0], [PLOT.w, 0], [PLOT.w, PLOT.d], [0, PLOT.d]]
    .forEach(c => pts.push(px(O.x + c[0], O.y + c[1], 0, s)));
  drawn.forEach(o => { pts.push(o.out.pin); pts.push([o.out.pin[0], o.out.pin[1] + 10]); });
  const xs = pts.map(p => p[0]), ys = pts.map(p => p[1]), pad = pitch * .1;
  const vb = {x: Math.min(...xs) - pad, y: Math.min(...ys) - pad * 1.4,
              w: Math.max(...xs) - Math.min(...xs) + pad * 2,
              h: Math.max(...ys) - Math.min(...ys) + pad * 2.2};
  const AR = opt.aspect || 2.45;
  if (vb.w / vb.h < AR) { const w = vb.h * AR; vb.x -= (w - vb.w) / 2; vb.w = w; }
  else { const h = vb.w / AR; vb.y -= (h - vb.h) / 2; vb.h = h; }

  const grid = [], step = pitch / 2;
  for (let gx = 0; gx <= PLOT.w; gx += step) {
    const a = px(O.x + gx, O.y, 0, s), b = px(O.x + gx, O.y + PLOT.d, 0, s);
    grid.push(`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}"/>`);
  }
  for (let gy = 0; gy <= PLOT.d; gy += step) {
    const a = px(O.x, O.y + gy, 0, s), b = px(O.x + PLOT.w, O.y + gy, 0, s);
    grid.push(`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}"/>`);
  }
  const plate = [[0, 0], [PLOT.w, 0], [PLOT.w, PLOT.d], [0, PLOT.d]]
    .map(c => px(O.x + c[0], O.y + c[1], 0, s).join(" ")).join(" ");
  const path = drawn.map((o, i) => (i ? "L" : "M") + o.out.foot[0] + " " + o.out.foot[1]).join(" ");

  const order = drawn.slice().sort((a, b) => a.out.depth - b.out.depth);
  const svg = `<svg class="land" viewBox="${vb.x} ${vb.y} ${vb.w} ${vb.h}" role="img"
      aria-label="An isometric drawing of ${plural(order.length, "product")} from the library, each at its published size">
    <polygon points="${plate}" fill="var(--iso-plate)"/>
    <g stroke="var(--iso-grid)" stroke-width=".9">${grid.join("")}</g>
    <path d="${path}" fill="none" stroke="var(--acc-2)" stroke-width="2.2" opacity=".5"
      stroke-linecap="round" stroke-dasharray="9 13" class="flow"/>
    ${order.map((o, i) => `<g class="obj" style="animation-delay:${180 + i * 110}ms">${o.out.svg}</g>`).join("")}
  </svg>`;

  const tallest = Math.max(...order.map(o => o.out.h));
  const placed = order.map(o => ({o: o, top: (o.out.pin[1] - vb.y) / vb.h * 100,
                                 left: (o.out.pin[0] - vb.x) / vb.w * 100}));
  const opener = placed.filter(q => q.top > 34).sort((a, b) => b.o.out.depth - a.o.out.depth)[0];
  const pins = placed.map((q, i) => `<a class="pin${q === opener ? " on" : ""}${q.top < 26 ? " below" : ""}"
      href="${q.o.r.href}" style="left:${q.left.toFixed(2)}%;top:${q.top.toFixed(2)}%;animation-delay:${420 + i * 110}ms">
      <span class="dot" aria-hidden="true"></span>
      <span class="tag"><b>${esc(q.o.r.model)}</b>${q.o.r.fact ? `<i>${esc(q.o.r.fact)}</i>` : ""}</span>
    </a>`).join("");
  return `<div class="land-wrap">${svg}${pins}</div>`;
}

/* ---- the product-family glyphs ----------------------------------------- */
function glyph(kind) {
  const W = ISO_W, B = ISO_B, solids = [];
  const box = (x, y, z, w, d, h, f) => solids.push([x, y, z, w, d, h, f]);
  let extra = "";

  if (kind === "design") {
    box(0, 0, 0, 62, 30, 84, W); box(80, 8, 0, 10, 10, 84, B); box(80, 8, 88, 10, 10, 6, B);
  } else if (kind === "core") {
    box(0, 0, 0, 78, 56, 9, W); box(0, 0, 16, 78, 56, 9, B);
    box(0, 0, 32, 78, 56, 9, W); box(0, 0, 48, 78, 56, 9, B);
  } else if (kind === "data") {
    for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) box(i * 34, j * 34, 0, 26, 26, 9, W);
    box(34, 34, 22, 26, 26, 9, B);
  } else if (kind === "market") {
    [30, 52, 78, 112].forEach((h, i) => box(i * 26, 0, 0, 17, 30, h, i === 3 ? B : W));
  } else if (kind === "health") {
    box(0, 0, 0, 54, 30, 88, W);
    [66, 48, 32, 18].forEach((h, i) => box(70 + i * 19, 6, 0, 12, 18, h, B));
  } else if (kind === "cup") {
    box(0, 0, 0, 32, 32, 54, W); box(36, 0, 0, 32, 32, 84, B); box(72, 0, 0, 32, 32, 38, W);
  } else if (kind === "recycle") {
    const at = [[0, 0], [92, 12], [42, 88]];
    at.forEach((a, i) => box(a[0], a[1], 0, 30, 26, 40 + i * 8, i === 1 ? B : W));
    const p = at.map(a => px(a[0] + 15, a[1] + 13, 0, 1));
    extra = `<path d="M${p[0][0]} ${p[0][1]} L${p[1][0]} ${p[1][1]} L${p[2][0]} ${p[2][1]} Z"
      fill="none" stroke="var(--acc-2)" stroke-width="2.6" stroke-dasharray="8 10"
      stroke-linecap="round" class="flow" opacity=".8"/>`;
  }

  const pts = [];
  solids.forEach(b => {
    for (const X of [b[0], b[0] + b[3]]) for (const Y of [b[1], b[1] + b[4]])
      for (const Z of [b[2], b[2] + b[5]]) pts.push(px(X, Y, Z, 1));
  });
  const xs = pts.map(p => p[0]), ys = pts.map(p => p[1]), m = 8;
  const vb = [Math.min(...xs) - m, Math.min(...ys) - m,
              Math.max(...xs) - Math.min(...xs) + m * 2, Math.max(...ys) - Math.min(...ys) + m * 2];
  const body = solids.sort((a, b) => (a[0] + a[1] + a[2] * .01) - (b[0] + b[1] + b[2] * .01))
    .map(b => isoBox(b[0], b[1], b[2], b[3], b[4], b[5], 1, b[6])).join("");
  return `<svg class="glyph" viewBox="${vb.join(" ")}" role="presentation" aria-hidden="true">${extra}${body}</svg>`;
}

/* ============================================================
   The cell under load — Rust, compiled to WebAssembly
   ------------------------------------------------------------
   Only the product pages load sim.js, so nobody downloads a
   physics model to look at a list. The inputs are worked out
   in Python and printed into the page, so this end only has to
   turn a slider into a call and a call into a curve.
   ============================================================ */
const SIM = {ready: false};
function labBoot() {
  if (typeof WebAssembly !== "object" || !window.BD_SIM_WASM) return;
  try {
    const bin = Uint8Array.from(atob(window.BD_SIM_WASM), c => c.charCodeAt(0));
    WebAssembly.instantiate(bin, {}).then(w => {
      const e = w.instance.exports;
      SIM.fn = e.simulate; SIM.mem = e.memory; SIM.ptr = e.out_ptr(); SIM.n = e.points();
      SIM.ready = true;
      if (window.BD_LAB) labMount(window.BD_LAB);
    }).catch(() => {});
  } catch (e) { /* a browser without WebAssembly still gets the whole page */ }
}

function labPlot(pts, inp, hot) {
  const W = 560, H = 300, L = 46, R = 12, TOP = 14, B = 34;
  if (!pts.length) return `<svg viewBox="0 0 ${W} ${H}"></svg>`;
  const maxAh = Math.max(inp.cap, pts[pts.length - 1][0]) || 1;
  const lo = Math.min(inp.vmin - .05, ...pts.map(q => q[1]));
  const hi = Math.max(inp.vmax, ...pts.map(q => q[1]));
  const X = a => L + (a / maxAh) * (W - L - R);
  const Y = v => TOP + (1 - (v - lo) / (hi - lo)) * (H - TOP - B);
  const line = pts.map((q, i) => (i ? "L" : "M") + X(q[0]).toFixed(1) + " " + Y(q[1]).toFixed(1)).join(" ");
  const area = line + ` L${X(pts[pts.length - 1][0]).toFixed(1)} ${Y(lo)} L${X(0)} ${Y(lo)} Z`;
  const vt = [], stepV = (hi - lo) > 1.2 ? .5 : .25;
  for (let v = Math.ceil(lo / stepV) * stepV; v <= hi; v += stepV) vt.push(v);
  const at = [0, .25, .5, .75, 1].map(f => f * maxAh);

  return `<svg viewBox="0 0 ${W} ${H}" role="img"
      aria-label="Terminal voltage against charge delivered, ${num(pts[pts.length - 1][0])} amp-hours to the cut-off">
    ${vt.map(v => `<line x1="${L}" y1="${Y(v).toFixed(1)}" x2="${W - R}" y2="${Y(v).toFixed(1)}"
        stroke="var(--hair)" stroke-width="1"/>
      <text x="${L - 8}" y="${(Y(v) + 4).toFixed(1)}" text-anchor="end" font-size="10.5"
        fill="var(--ink-3)">${v.toFixed(2).replace(/0$/, "")}</text>`).join("")}
    ${at.map(a => `<text x="${X(a).toFixed(1)}" y="${H - 12}" text-anchor="middle" font-size="10.5"
        fill="var(--ink-3)">${num(a)}</text>`).join("")}
    <text x="${L - 8}" y="${TOP + 2}" text-anchor="end" font-size="10" fill="var(--ink-3)">V</text>
    <text x="${W - R}" y="${TOP + 2}" text-anchor="end" font-size="10" fill="var(--ink-3)">Ah delivered</text>
    <line x1="${L}" y1="${Y(inp.vmin).toFixed(1)}" x2="${W - R}" y2="${Y(inp.vmin).toFixed(1)}"
      stroke="var(--flag)" stroke-width="1.2" stroke-dasharray="5 5" opacity=".85"/>
    <text x="${L + 6}" y="${(Y(inp.vmin) - 6).toFixed(1)}" font-size="10.5"
      fill="var(--flag)">cut-off ${num(inp.vmin)} V</text>
    <path d="${area}" fill="url(#labFill)"/>
    <path d="${line}" fill="none" stroke="${hot ? "var(--flag)" : "var(--acc-1)"}" stroke-width="2.6"
      stroke-linejoin="round" stroke-linecap="round"/>
    <circle cx="${X(pts[pts.length - 1][0]).toFixed(1)}" cy="${Y(pts[pts.length - 1][1]).toFixed(1)}" r="4.5"
      fill="var(--bg)" stroke="${hot ? "var(--flag)" : "var(--acc-1)"}" stroke-width="2.4"/>
  </svg>`;
}

function labMount(inp) {
  const cS = document.getElementById("labC"), tS = document.getElementById("labT");
  if (!cS || !SIM.ready) return;
  const set = (id, v, u) => { document.getElementById(id).innerHTML = v + (u ? `<small>${u}</small>` : ""); };
  let queued = false;

  function draw() {
    queued = false;
    const c = +cS.value / 100, t = +tS.value;
    cS.style.setProperty("--pct", (cS.value - cS.min) / (cS.max - cS.min) * 100 + "%");
    tS.style.setProperty("--pct", (tS.value - tS.min) / (tS.max - tS.min) * 100 + "%");
    document.getElementById("labCV").textContent = c.toFixed(2).replace(/0$/, "") + " C";
    document.getElementById("labTV").textContent = t + " °C";

    const n = SIM.fn(inp.cap, inp.vmax, inp.vmin, inp.r, inp.mass, c, t, inp.flat ? 1 : 0);
    const f = new Float32Array(SIM.mem.buffer, SIM.ptr, SIM.n * 3 + 16);
    const pts = [];
    for (let i = 0; i < n; i++) pts.push([f[i] * inp.cap, f[SIM.n + i]]);
    const s = i => f[SIM.n * 3 + i];

    document.getElementById("labplot").innerHTML = labPlot(pts, inp, s(6) > 12);
    set("labAh", num(s(0)), "Ah");
    set("labWh", num(s(1)), "Wh");
    const secs = s(3);
    document.getElementById("labT2").textContent = secs >= 3600
      ? (secs / 3600).toFixed(1) + " h" : Math.round(secs / 60) + " min";
    set("labPct", Math.round(s(7) * 100), "%");
    set("labWhkg", inp.mass ? num(s(2)) : "—", inp.mass ? "Wh/kg" : "");
    set("labDT", inp.mass ? "+" + num(s(6)) : "—", inp.mass ? "K" : "");
    document.getElementById("labCA").textContent = num(s(8)) + " A out of a " + num(inp.cap) + " Ah cell";
    document.querySelectorAll("#labPre button").forEach(b =>
      b.setAttribute("aria-pressed", +b.dataset.c === +cS.value && +b.dataset.t === +tS.value));
  }
  /* one draw per frame however fast the slider is dragged */
  const run = () => { if (!queued) { queued = true; requestAnimationFrame(draw); } };

  cS.addEventListener("input", run);
  tS.addEventListener("input", run);
  document.getElementById("labPre").addEventListener("click", e => {
    const b = e.target.closest("button[data-c]");
    if (!b) return;
    cS.value = b.dataset.c; tS.value = b.dataset.t; draw();
  });
  draw();
}

/* ============================================================
   Page furniture
   ============================================================ */
function reveal() {
  const nodes = document.querySelectorAll(".rev:not(.in)");
  if (!("IntersectionObserver" in window) || matchMedia("(prefers-reduced-motion: reduce)").matches) {
    nodes.forEach(n => n.classList.add("in"));
    return;
  }
  const io = new IntersectionObserver(es => {
    es.forEach(e => { if (e.isIntersecting) { e.target.classList.add("in"); io.unobserve(e.target); } });
  }, {rootMargin: "0px 0px -8% 0px", threshold: .05});
  nodes.forEach(n => io.observe(n));
}

function navSkin() {
  const nav = document.querySelector(".nav");
  if (nav) nav.classList.toggle("over", document.body.dataset.overhero === "1" && scrollY < 34);
}

/* The search overlay reads the lean index every page already carries. */
function bootSearch() {
  const wrap = document.getElementById("searchwrap");
  if (!wrap || !window.BD) return;
  const input = document.getElementById("searchinput"), list = document.getElementById("results");
  const P = window.BD.products;
  let hits = [], cursor = 0;
  input.placeholder = "Search " + P.length + " products";

  const open = () => { wrap.classList.add("on"); input.value = ""; draw(""); input.focus(); };
  const close = () => wrap.classList.remove("on");

  function draw(q) {
    const s = q.trim().toLowerCase();
    hits = (s ? P.filter(p => p.hay.includes(s)) : P).slice(0, 40);
    cursor = 0;
    list.innerHTML = hits.length ? hits.map((p, i) => `<a href="${p.href}" class="${i ? "" : "on"}">
        <span>${esc(p.name)}</span><span class="s">${esc(p.sub)}</span></a>`).join("")
      : `<p class="empty">Nothing by that name yet.</p>`;
  }
  function move(d) {
    const nodes = list.querySelectorAll("a"); if (!nodes.length) return;
    nodes[cursor].classList.remove("on");
    cursor = (cursor + d + nodes.length) % nodes.length;
    nodes[cursor].classList.add("on");
    nodes[cursor].scrollIntoView({block: "nearest"});
  }
  document.getElementById("searchbtn").addEventListener("click", open);
  input.addEventListener("input", e => draw(e.target.value));
  list.addEventListener("click", close);
  wrap.addEventListener("click", e => { if (e.target === wrap) close(); });
  addEventListener("keydown", e => {
    if (e.key === "/" && !/^(INPUT|SELECT|TEXTAREA)$/.test(document.activeElement.tagName)) {
      e.preventDefault(); open(); return;
    }
    if (!wrap.classList.contains("on")) return;
    if (e.key === "Escape") close();
    else if (e.key === "ArrowDown") { e.preventDefault(); move(1); }
    else if (e.key === "ArrowUp") { e.preventDefault(); move(-1); }
    else if (e.key === "Enter") { const a = list.querySelectorAll("a")[cursor]; if (a) location.href = a.href; }
  });
}

/* Draw whatever this page asked for, once it is parsed. */
function boot() {
  document.body.insertAdjacentHTML("afterbegin", SPRITE);
  /* Drawings are made when they are about to be seen. A library page holds 64
     of them and shows six; drawing the other 58 up front is work nobody asked
     for, and DOM nobody looks at. */
  const byUid = (window.BD && window.BD.byUid) || {};
  const draw = n => {
    const r = byUid[n.dataset.art];
    if (r) n.innerHTML = art(r, {max: +n.dataset.max || 150, reflect: n.dataset.reflect === "1"}).svg;
  };
  const slots = document.querySelectorAll("[data-art]");
  if ("IntersectionObserver" in window && slots.length > 6) {
    const io = new IntersectionObserver(es => {
      es.forEach(x => { if (x.isIntersecting) { draw(x.target); io.unobserve(x.target); } });
    }, {rootMargin: "500px 0px"});
    slots.forEach(n => io.observe(n));
  } else {
    slots.forEach(draw);
  }
  document.querySelectorAll("[data-glyph]").forEach(n => { n.innerHTML = glyph(n.dataset.glyph); });
  const land = document.getElementById("land");
  if (land && window.BD) land.innerHTML = landscape(window.BD.scene || [], {});
  navSkin();
  addEventListener("scroll", navSkin, {passive: true});
  reveal();
  bootSearch();
  if (window.BD_LAB) labBoot();
}
if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
else boot();
